language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=notes
  matrix:
    - DB=mysql

branches:
  only:
    - master
    - /^stable\d*$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - . ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server/
  - php occ app:enable notes
  - cd apps/$APP_NAME

script:
  - phpunit -c phpunit.integration.xml

matrix:
  include:
    - php: 5.6
      env: "DB=mysql CORE_BRANCH=stable11"
    - php: 5.6
      env: "DB=mysql CORE_BRANCH=stable10"
  fast_finish: true
