language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=notes
  matrix:
    - DB=mysql

branches:
  only:
    - master
    - /^stable\d*$/

before_install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install firefox
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../core/apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;
  - phpunit --coverage-clover clover.xml -c phpunit.xml
  - phpunit -c phpunit.integration.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

  # execute js tests
  - cd js
  - npm install
  - npm install -g gulp
  - gulp test

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

matrix:
  include:
    - php: 5.4
      env: DB=sqlite
    - php: 5.4
      env: DB=pgsql
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true